# Site Settings
title: Resume
url: 'http://arkenstonesolutions.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Kiran Bollepalli
tagline: Mobile Application Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am 8 years experienced Mobile application developer. 
I have a solid background in creating complex mobile applications for Android.
I can work independently and respect a deadline.
I feel comfortable working with a good team of developers.
 I am passionate about the mobile marketing and have knowledge about.
'

#sidebar links
email: kiranbollepalli@gmail.com
phone: +91 8892344003
website: arkenstonesolutions.com #do not add http://
linkedin: kiran-bollepalli
github: kiranbollepalli9
twitter: '@kiranbollepalli'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
